name: nlp-env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - huggingface
  - defaults
dependencies:
  - openssl=1.1.1q
  - pyopenssl=22.0.0
  - numpy=1.21.5
  - numba=0.55.1
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - scikit-learn=1.0.2
  - pandas=1.4.4
  - tqdm=4.64.1
  - re2=2022.04.01
  - regex=2022.7.9
  - requests=2.28.1
  - optuna=2.10.1
  - pathlib=1.0.1
  - joblib=1.1.0
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.3
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.5.2
  - nltk=3.7
  - transformers=4.21.0
  - langdetect